version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: scholarbridge_db
    environment:
      POSTGRES_DB: scholarbridge_lms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - scholarbridge_network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: scholarbridge_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - scholarbridge_network

  # Backend API Server
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: scholarbridge_api
    environment:
      NODE_ENV: development
      PORT: 5000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: scholarbridge_lms
      DB_USER: postgres
      DB_PASSWORD: postgres123
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      JWT_REFRESH_SECRET: your-super-secret-refresh-key-change-in-production
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - scholarbridge_network

  # Frontend React App
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: scholarbridge_client
    environment:
      REACT_APP_API_URL: http://localhost:5000/api
      REACT_APP_SOCKET_URL: http://localhost:5000
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - scholarbridge_network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: scholarbridge_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - api
      - client
    networks:
      - scholarbridge_network

volumes:
  postgres_data:
  redis_data:

networks:
  scholarbridge_network:
    driver: bridge